name: Install and testrun CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  gcc-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: "Boost"
      run: sudo apt install libboost-dev-all
    - name: "Configure and make (C++)"
      run: |
        make -C src all
        
  java-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: "Make one class-file"
      run: |
        echo "Making one class-file"
        make -C Java src/ImageMaker/GenerateImages.class
    - name: "Make jarfiles"
      run: |
        echo "Running java jarfiles"
        make -C Java jarfiles
        :
     
  build:
    runs-on: ubuntu-latest
    needs: [java-build, gcc-build]
    steps:
    - uses: actions/checkout@v2
    - name: "Install Boost"
      run: sudo apt install libboost-dev-all
    - name: make
      run: make
    - name: make install
      run: make install
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: "Install everything"
      run: |
        echo Running install
        make install
    - name: "Run a simple graph"
      run: |
        cd scripts
        echo Trying to create graph
        ./creategraphfromdate.sh 2000 09
    - name: Upload Example binary
      uses: actions/upload-artifact@v1
      with:
        name: Upload graph
        path: testrun/bview_2000_09/bview_2000_09_transparent.png