name: Build and install CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  gcc-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: "Boost"
      run: sudo apt install libboost-all-dev
    - name: "Configure and make (C++)"
      run: |
        make -C src all
        
  java-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: "Make one class-file"
      run: |
        echo "Making one class-file"
        make -C Java src/ImageMaker/GenerateImages.class
    - name: "Make jarfiles"
      run: |
        echo "Running java jarfiles"
        make -C Java jarfiles
        :
     
  build:
    runs-on: ubuntu-latest
    needs: [java-build, gcc-build]
    steps:
    - uses: actions/checkout@v2
    - name: "Install Boost"
      run: sudo apt install libboost-all-dev
    - name: make
      run: make
    - name: make install
      run: make install
