name: Java jars build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: "Make one class-file"
      run: |
        echo "Making one class-file"
        make -C Java src/ImageMaker/GenerateImages.class
    - name: "Make jarfiles"
      run: |
        echo "Running java jarfiles"
        make -C Java jarfiles
        
