name: Test simple graph (Internet 2000)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: "Run a simple graph"
      run: |
        cd scripts
        echo Trying to create graph
        ./creategraphfromdate.sh 2000 09

